using System.Text;

namespace FolderDiffIL4DotNet.Services
{
    // JavaScript for localStorage auto-save, download-as-reviewed, lazy diff rendering, and column resizing.
    // localStorage 自動保存・レビュー済みダウンロード・遅延差分描画・カラムリサイズ用 JavaScript。
    public sealed partial class HtmlReportGenerateService
    {
        private static void AppendJs(StringBuilder sb, string storageKey, string reportDate)
        {
            sb.AppendLine("<script>");
            sb.AppendLine($"  const __storageKey__  = '{storageKey}';");
            sb.AppendLine($"  const __reportDate__  = '{reportDate}';");
            // NOTE: 'const __savedState__ = null;' is replaced by downloadReviewed(). Do not change whitespace.
            sb.AppendLine("  const __savedState__  = null;");
            sb.AppendLine();
            sb.AppendLine("  function formatTs(d) {");
            sb.AppendLine("    return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')");
            sb.AppendLine("      +' '+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')+':'+String(d.getSeconds()).padStart(2,'0');");
            sb.AppendLine("  }");
            sb.AppendLine();
            sb.AppendLine("  document.addEventListener('DOMContentLoaded', function() {");
            sb.AppendLine("    var toRestore = __savedState__ || JSON.parse(localStorage.getItem(__storageKey__) || 'null');");
            sb.AppendLine("    if (toRestore) {");
            sb.AppendLine("      Object.entries(toRestore).forEach(function(entry) {");
            sb.AppendLine("        var el = document.getElementById(entry[0]);");
            sb.AppendLine("        if (!el) return;");
            sb.AppendLine("        if (el.type === 'checkbox') el.checked = Boolean(entry[1]);");
            sb.AppendLine("        else el.value = String(entry[1] || '');");
            sb.AppendLine("      });");
            sb.AppendLine("    }");
            // If this is a reviewed/downloaded copy, lock all inputs
            sb.AppendLine("    if (__savedState__ !== null) {");
            sb.AppendLine("      document.querySelectorAll('input[type=\"checkbox\"]').forEach(function(cb){ cb.style.pointerEvents='none'; cb.style.cursor='default'; });");
            sb.AppendLine("      document.querySelectorAll('input[type=\"text\"]').forEach(function(inp){");
            sb.AppendLine("        inp.readOnly=true; inp.style.cursor='default'; inp.style.userSelect='text';");
            sb.AppendLine("      });");
            sb.AppendLine("    } else {");
            sb.AppendLine("      document.querySelectorAll('input, textarea').forEach(function(el) {");
            sb.AppendLine("        el.addEventListener('change', autoSave);");
            sb.AppendLine("        el.addEventListener('input',  autoSave);");
            sb.AppendLine("      });");
            sb.AppendLine("    }");
            sb.AppendLine("    initColResize();");
            sb.AppendLine("    syncTableWidths();");
            sb.AppendLine("    syncScTableWidths();");
            sb.AppendLine("    setupLazyDiff();");
            sb.AppendLine("  });");
            sb.AppendLine();
            sb.AppendLine("  function collectState() {");
            sb.AppendLine("    var s = {};");
            sb.AppendLine("    document.querySelectorAll('input[id], textarea[id]').forEach(function(el) {");
            sb.AppendLine("      s[el.id] = (el.type === 'checkbox') ? el.checked : el.value;");
            sb.AppendLine("    });");
            sb.AppendLine("    return s;");
            sb.AppendLine("  }");
            sb.AppendLine();
            sb.AppendLine("  function autoSave() {");
            sb.AppendLine("    localStorage.setItem(__storageKey__, JSON.stringify(collectState()));");
            sb.AppendLine("    var status = document.getElementById('save-status');");
            sb.AppendLine("    if (status) status.textContent = 'Auto-saved at ' + formatTs(new Date());");
            sb.AppendLine("  }");
            sb.AppendLine();
            sb.AppendLine("  function downloadReviewed() {");
            sb.AppendLine("    var state   = collectState();");
            sb.AppendLine("    var slug    = 'diff_report_' + __reportDate__;");
            sb.AppendLine("    var root    = document.documentElement;");
            sb.AppendLine("    // 1. Collapse all diff-detail elements so exported file starts with diffs closed");
            sb.AppendLine("    var openDetails = Array.from(document.querySelectorAll('details[open]'));");
            sb.AppendLine("    openDetails.forEach(function(d){ d.removeAttribute('open'); });");
            sb.AppendLine("    // 2. Capture current effective column widths to bake into reviewed HTML as defaults");
            sb.AppendLine("    var colVarNames = ['--col-reason-w','--col-notes-w','--col-path-w','--col-diff-w','--col-disasm-w','--sc-class-w','--sc-basetype-w','--sc-type-w','--sc-name-w','--sc-rettype-w','--sc-params-w','--sc-body-w','--sc-cnt-class-w'];");
            sb.AppendLine("    var cs = getComputedStyle(root);");
            sb.AppendLine("    var curWidths = {};");
            sb.AppendLine("    colVarNames.forEach(function(v){ curWidths[v] = (root.style.getPropertyValue(v) || cs.getPropertyValue(v)).trim(); });");
            sb.AppendLine("    var html    = document.documentElement.outerHTML;");
            sb.AppendLine("    // Restore open details in the live page");
            sb.AppendLine("    openDetails.forEach(function(d){ d.setAttribute('open', ''); });");
            sb.AppendLine("    // Embed state");
            sb.AppendLine("    html = html.replace('const __savedState__  = null;',");
            sb.AppendLine("      'const __savedState__  = ' + JSON.stringify(state) + ';');");
            sb.AppendLine("    // Update title");
            sb.AppendLine("    html = html.replace('<title>diff_report</title>',");
            sb.AppendLine("      '<title>' + slug + '_reviewed</title>');");
            sb.AppendLine("    // Bake current column widths as CSS defaults in the reviewed HTML");
            sb.AppendLine("    html = html.replace(/:root \\{ --col-reason-w:[^}]+\\}/,");
            sb.AppendLine("      ':root { --col-reason-w: '  + curWidths['--col-reason-w']");
            sb.AppendLine("      + '; --col-notes-w: '   + curWidths['--col-notes-w']");
            sb.AppendLine("      + '; --col-path-w: '    + curWidths['--col-path-w']");
            sb.AppendLine("      + '; --col-diff-w: '    + curWidths['--col-diff-w']");
            sb.AppendLine("      + '; --col-disasm-w: '  + curWidths['--col-disasm-w']");
            sb.AppendLine("      + '; --sc-class-w: '    + curWidths['--sc-class-w']");
            sb.AppendLine("      + '; --sc-basetype-w: ' + curWidths['--sc-basetype-w']");
            sb.AppendLine("      + '; --sc-type-w: '     + curWidths['--sc-type-w']");
            sb.AppendLine("      + '; --sc-name-w: '     + curWidths['--sc-name-w']");
            sb.AppendLine("      + '; --sc-rettype-w: '  + curWidths['--sc-rettype-w']");
            sb.AppendLine("      + '; --sc-params-w: '   + curWidths['--sc-params-w']");
            sb.AppendLine("      + '; --sc-body-w: '     + curWidths['--sc-body-w']");
            sb.AppendLine("      + '; --sc-cnt-class-w: ' + curWidths['--sc-cnt-class-w'] + '; }');");
            sb.AppendLine("    // Remove inline col-var overrides from <html> element (now baked into :root)");
            sb.AppendLine("    html = html.replace(/(<html\\b[^>]*?) style=\"[^\"]*\"/, '$1');");
            sb.AppendLine("    // Replace controls bar with reviewed banner");
            sb.AppendLine("    html = html.replace(/<!--CTRL-->[\\s\\S]*?<!--\\/CTRL-->/g,");
            sb.AppendLine("      '<div class=\"reviewed-banner\">&#x1F512; Reviewed: ' + formatTs(new Date()) + ' &#x2014; read-only</div>');");
            sb.AppendLine("    var blob = new Blob([html], { type: 'text/html;charset=utf-8' });");
            sb.AppendLine("    var a    = document.createElement('a');");
            sb.AppendLine("    a.href   = URL.createObjectURL(blob);");
            sb.AppendLine("    a.download = slug + '_reviewed.html';");
            sb.AppendLine("    document.body.appendChild(a);");
            sb.AppendLine("    a.click();");
            sb.AppendLine("    document.body.removeChild(a);");
            sb.AppendLine("    setTimeout(function(){ URL.revokeObjectURL(a.href); }, 1000);");
            sb.AppendLine("  }");
            sb.AppendLine();
            sb.AppendLine("  function collapseAll() {");
            sb.AppendLine("    document.querySelectorAll('details[open]').forEach(function(d){ d.removeAttribute('open'); });");
            sb.AppendLine("    scheduleSave();");
            sb.AppendLine("  }");
            sb.AppendLine();
            sb.AppendLine("  function clearAll() {");
            sb.AppendLine("    if (!confirm('Clear all checkboxes and text inputs?')) return;");
            sb.AppendLine("    document.querySelectorAll('input[type=\"checkbox\"]').forEach(function(cb){ cb.checked=false; });");
            sb.AppendLine("    document.querySelectorAll('input[type=\"text\"], textarea').forEach(function(inp){ inp.value=''; });");
            sb.AppendLine("    // Reset column widths to defaults");
            sb.AppendLine("    var root = document.documentElement;");
            sb.AppendLine("    ['--col-reason-w','--col-notes-w','--col-path-w','--col-diff-w','--col-disasm-w','--sc-class-w','--sc-basetype-w','--sc-type-w','--sc-name-w','--sc-rettype-w','--sc-params-w','--sc-body-w','--sc-cnt-class-w'].forEach(function(v){ root.style.removeProperty(v); });");
            sb.AppendLine("    syncTableWidths();");
            sb.AppendLine("    // Close all open diff/IL-diff details");
            sb.AppendLine("    document.querySelectorAll('details[open]').forEach(function(d){ d.removeAttribute('open'); });");
            sb.AppendLine("    localStorage.removeItem(__storageKey__);");
            sb.AppendLine("    var status = document.getElementById('save-status');");
            sb.AppendLine("    if (status) status.textContent = 'Cleared.';");
            sb.AppendLine("  }");
            sb.AppendLine();
            sb.AppendLine("  function decodeDiffHtml(b64) {");
            sb.AppendLine("    var binary = atob(b64);");
            sb.AppendLine("    var bytes = new Uint8Array(binary.length);");
            sb.AppendLine("    for (var i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);");
            sb.AppendLine("    return new TextDecoder('utf-8').decode(bytes);");
            sb.AppendLine("  }");
            sb.AppendLine();
            sb.AppendLine("  // Lazy-render: diff table HTML is stored base64-encoded in data-diff-html.");
            sb.AppendLine("  // On first open, decode and insert into DOM, then remove the attribute.");
            sb.AppendLine("  function setupLazyDiff() {");
            sb.AppendLine("    document.querySelectorAll('details[data-diff-html]').forEach(function(d) {");
            sb.AppendLine("      d.addEventListener('toggle', function onToggle() {");
            sb.AppendLine("        if (!d.open) return;");
            sb.AppendLine("        var b64 = d.getAttribute('data-diff-html');");
            sb.AppendLine("        if (!b64) return;");
            sb.AppendLine("        d.removeAttribute('data-diff-html');");
            sb.AppendLine("        d.removeEventListener('toggle', onToggle);");
            sb.AppendLine("        try {");
            sb.AppendLine("          d.insertAdjacentHTML('beforeend', decodeDiffHtml(b64));");
            sb.AppendLine("          // Re-init column resize handles on newly rendered tables");
            sb.AppendLine("          d.querySelectorAll('th.th-resizable').forEach(function(th) {");
            sb.AppendLine("            if (th.querySelector('.col-resize-handle')) return;");
            sb.AppendLine("            initColResizeSingle(th);");
            sb.AppendLine("          });");
            sb.AppendLine("          syncScTableWidths();");
            sb.AppendLine("          // Wire up save events on new checkboxes");
            sb.AppendLine("          if (__savedState__ === null) {");
            sb.AppendLine("            d.querySelectorAll('input').forEach(function(el) {");
            sb.AppendLine("              el.addEventListener('change', autoSave);");
            sb.AppendLine("            });");
            sb.AppendLine("          }");
            sb.AppendLine("          // Restore state for new inputs");
            sb.AppendLine("          var toRestore = __savedState__ || JSON.parse(localStorage.getItem(__storageKey__) || 'null');");
            sb.AppendLine("          if (toRestore) {");
            sb.AppendLine("            d.querySelectorAll('input[id]').forEach(function(el) {");
            sb.AppendLine("              if (el.id in toRestore) {");
            sb.AppendLine("                if (el.type === 'checkbox') el.checked = Boolean(toRestore[el.id]);");
            sb.AppendLine("                else el.value = String(toRestore[el.id] || '');");
            sb.AppendLine("              }");
            sb.AppendLine("            });");
            sb.AppendLine("          }");
            sb.AppendLine("          if (__savedState__ !== null) {");
            sb.AppendLine("            d.querySelectorAll('input[type=\"checkbox\"]').forEach(function(cb){ cb.style.pointerEvents='none'; cb.style.cursor='default'; });");
            sb.AppendLine("          }");
            sb.AppendLine("        } catch(e) {}");
            sb.AppendLine("      });");
            sb.AppendLine("    });");
            sb.AppendLine("  }");
            sb.AppendLine();
            sb.AppendLine("  function syncTableWidths() {");
            sb.AppendLine("    var root = document.documentElement;");
            sb.AppendLine("    var emPx = parseFloat(getComputedStyle(root).fontSize) || 16;");
            sb.AppendLine("    var px = function(v, fb) {");
            sb.AppendLine("      var s = root.style.getPropertyValue(v) || getComputedStyle(root).getPropertyValue(v);");
            sb.AppendLine("      return (parseFloat(s) || fb) * emPx;");
            sb.AppendLine("    };");
            sb.AppendLine("    var w = (3.2 + 2.2 + 16) * emPx");
            sb.AppendLine("          + px('--col-reason-w', 10) + px('--col-notes-w', 10)");
            sb.AppendLine("          + px('--col-path-w', 22)   + px('--col-diff-w', 9)");
            sb.AppendLine("          + px('--col-disasm-w', 28);");
            sb.AppendLine("    document.querySelectorAll('table:not(.stat-table):not(.diff-table):not(.semantic-changes-table)').forEach(function(t) {");
            sb.AppendLine("      t.style.width = w + 'px';");
            sb.AppendLine("    });");
            sb.AppendLine("  }");
            sb.AppendLine();
            sb.AppendLine("  function syncScTableWidths() {");
            sb.AppendLine("    var scEmPx = 12;");
            sb.AppendLine("    var root = document.documentElement;");
            sb.AppendLine("    var px = function(v, fb) {");
            sb.AppendLine("      var s = root.style.getPropertyValue(v) || getComputedStyle(root).getPropertyValue(v);");
            sb.AppendLine("      return (parseFloat(s) || fb) * scEmPx;");
            sb.AppendLine("    };");
            sb.AppendLine("    var detW = 3.2 * scEmPx");
            sb.AppendLine("            + px('--sc-class-w', 14) + px('--sc-basetype-w', 16)");
            sb.AppendLine("            + 7 * scEmPx + 10 * scEmPx + 8 * scEmPx + 11 * scEmPx");
            sb.AppendLine("            + px('--sc-type-w', 12) + px('--sc-name-w', 10)");
            sb.AppendLine("            + px('--sc-rettype-w', 12) + px('--sc-params-w', 18)");
            sb.AppendLine("            + px('--sc-body-w', 5);");
            sb.AppendLine("    document.querySelectorAll('table.sc-detail').forEach(function(t) { t.style.width = detW + 'px'; });");
            sb.AppendLine("    var cntW = px('--sc-cnt-class-w', 22) + 7 * scEmPx + 4 * scEmPx;");
            sb.AppendLine("    document.querySelectorAll('table.sc-count').forEach(function(t) { t.style.width = cntW + 'px'; });");
            sb.AppendLine("  }");
            sb.AppendLine();
            sb.AppendLine("  function initColResizeSingle(th) {");
            sb.AppendLine("    var label = document.createElement('span');");
            sb.AppendLine("    label.className = 'th-label';");
            sb.AppendLine("    while (th.childNodes.length) label.appendChild(th.childNodes[0]);");
            sb.AppendLine("    th.appendChild(label);");
            sb.AppendLine("    var handle = document.createElement('div');");
            sb.AppendLine("    handle.className = 'col-resize-handle';");
            sb.AppendLine("    th.appendChild(handle);");
            sb.AppendLine("    var varName = th.dataset.colVar;");
            sb.AppendLine("    var isSc = !!th.closest('.semantic-changes-table');");
            sb.AppendLine("    handle.addEventListener('mousedown', function(e) {");
            sb.AppendLine("      e.preventDefault();");
            sb.AppendLine("      var startX = e.clientX;");
            sb.AppendLine("      var root   = document.documentElement;");
            sb.AppendLine("      var emPx   = isSc ? 12 : (parseFloat(getComputedStyle(root).fontSize) || 16);");
            sb.AppendLine("      var cur    = root.style.getPropertyValue(varName) || getComputedStyle(root).getPropertyValue(varName);");
            sb.AppendLine("      var startPx = (parseFloat(cur) || 10) * emPx;");
            sb.AppendLine("      function onMove(ev) {");
            sb.AppendLine("        var newPx = Math.max(48, startPx + (ev.clientX - startX));");
            sb.AppendLine("        root.style.setProperty(varName, (newPx / emPx).toFixed(2) + 'em');");
            sb.AppendLine("        syncTableWidths();");
            sb.AppendLine("        if (isSc) syncScTableWidths();");
            sb.AppendLine("      }");
            sb.AppendLine("      function onUp() {");
            sb.AppendLine("        document.removeEventListener('mousemove', onMove);");
            sb.AppendLine("        document.removeEventListener('mouseup', onUp);");
            sb.AppendLine("      }");
            sb.AppendLine("      document.addEventListener('mousemove', onMove);");
            sb.AppendLine("      document.addEventListener('mouseup', onUp);");
            sb.AppendLine("    });");
            sb.AppendLine("  }");
            sb.AppendLine();
            sb.AppendLine("  function initColResize() {");
            sb.AppendLine("    document.querySelectorAll('th.th-resizable').forEach(function(th) {");
            sb.AppendLine("      initColResizeSingle(th);");
            sb.AppendLine("    });");
            sb.AppendLine("  }");
            sb.AppendLine();
            sb.AppendLine("  function copyPath(btn) {");
            sb.AppendLine("    var td = btn.closest('td');");
            sb.AppendLine("    if (!td) return;");
            sb.AppendLine("    var span = td.querySelector('.path-text');");
            sb.AppendLine("    var text = span ? span.textContent.trim() : td.textContent.trim();");
            sb.AppendLine("    if (!text) return;");
            sb.AppendLine("    navigator.clipboard.writeText(text).then(function() {");
            sb.AppendLine("      var svg = btn.querySelector('svg');");
            sb.AppendLine("      if (svg) { svg.style.display='none'; btn.textContent='\\u2713'; }");
            sb.AppendLine("      setTimeout(function() {");
            sb.AppendLine("        if (svg) { btn.textContent=''; btn.appendChild(svg); svg.style.display=''; }");
            sb.AppendLine("      }, 1200);");
            sb.AppendLine("    });");
            sb.AppendLine("  }");
            sb.AppendLine("</script>");
        }
    }
}
